---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ljwx-health

resources:
  - namespace.yaml
  - configmap.yaml
  - job-init-db.yaml
  - job-flyway-repair.yaml
  - deployment-boot.yaml
  - deployment-admin.yaml
  - deployment-bigscreen.yaml
  - service-boot.yaml
  - service-admin.yaml
  - service-bigscreen.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: ljwx-health
  app.kubernetes.io/managed-by: kustomize
