apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ljwx-platform
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - platform.lingjingwanxiang.cn
      secretName: ljwx-platform-tls
    - hosts:
        - platform-screen.lingjingwanxiang.cn
      secretName: ljwx-platform-screen-tls
  rules:
    - host: platform.lingjingwanxiang.cn
      http:
        paths:
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: ljwx-platform-admin-ui
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ljwx-platform
                port:
                  number: 8080
    - host: platform-screen.lingjingwanxiang.cn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ljwx-platform-screen
                port:
                  number: 80
