apiVersion: v1
kind: Service
metadata:
  name: ljwx-platform
spec:
  selector:
    app: ljwx-platform
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP

