apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ljwx-platform
resources:
- ../../base
images:
- name: harbor.eu.lingjingwanxiang.cn/ljwx-platform/ljwx-platform
  newName: harbor.eu.lingjingwanxiang.cn/ljwx/ljwx-platform
  newTag: a849339c6c74fcf82b2a868de5add4229eb27c2a
- name: harbor.eu.lingjingwanxiang.cn/ljwx/ljwx-platform-admin-ui
  newName: harbor.eu.lingjingwanxiang.cn/ljwx/ljwx-platform-admin-ui
  newTag: a849339c6c74fcf82b2a868de5add4229eb27c2a
- name: harbor.eu.lingjingwanxiang.cn/ljwx/ljwx-platform-screen
  newName: harbor.eu.lingjingwanxiang.cn/ljwx/ljwx-platform-screen
  newTag: a849339c6c74fcf82b2a868de5add4229eb27c2a
