apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ljwx-platform
resources:
- ../../base
images:
- name: harbor.eu.lingjingwanxiang.cn/ljwx-platform/ljwx-platform
  newName: harbor.eu.lingjingwanxiang.cn/ljwx/ljwx-platform
  newTag: d0f41310385bbfe240402d2a795840dfd267291e
- name: harbor.eu.lingjingwanxiang.cn/ljwx/ljwx-platform-admin-ui
  newName: harbor.eu.lingjingwanxiang.cn/ljwx/ljwx-platform-admin-ui
  newTag: d0f41310385bbfe240402d2a795840dfd267291e
- name: harbor.eu.lingjingwanxiang.cn/ljwx/ljwx-platform-screen
  newName: harbor.eu.lingjingwanxiang.cn/ljwx/ljwx-platform-screen
  newTag: d0f41310385bbfe240402d2a795840dfd267291e
