apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ljwx-platform
resources:
- ../../base
images:
- name: harbor.eu.lingjingwanxiang.cn/ljwx-platform/ljwx-platform
  newName: harbor.eu.lingjingwanxiang.cn/ljwx/ljwx-platform
  newTag: a0a918148441fc76d1855aeff0508353e8501498
- name: harbor.eu.lingjingwanxiang.cn/ljwx/ljwx-platform-admin-ui
  newName: harbor.eu.lingjingwanxiang.cn/ljwx/ljwx-platform-admin-ui
  newTag: a0a918148441fc76d1855aeff0508353e8501498
- name: harbor.eu.lingjingwanxiang.cn/ljwx/ljwx-platform-screen
  newName: harbor.eu.lingjingwanxiang.cn/ljwx/ljwx-platform-screen
  newTag: a0a918148441fc76d1855aeff0508353e8501498
