apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ljwx-platform

resources:
  - ../../base

images:
  - name: harbor.eu.lingjingwanxiang.cn/ljwx-platform/ljwx-platform
    newName: harbor.eu.lingjingwanxiang.cn/ljwx/ljwx-platform
    newTag: sha-6f0d62edf790

