apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra

resources:
  - create-db-script.yaml
  - rbac.yaml
  # provision-job.yaml is not included here
  # It should be manually created for each project/env

commonLabels:
  app.kubernetes.io/name: postgres
  app.kubernetes.io/component: provisioning
  app.kubernetes.io/managed-by: gitops
