apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra

resources:
  - configmap.yaml
  - pvc.yaml
  - backup-full-cronjob.yaml
  - backup-diff-cronjob.yaml
  # restore-job-template.yaml is not included here
  # It should be manually created when needed

commonLabels:
  app.kubernetes.io/name: postgres
  app.kubernetes.io/component: backup
  app.kubernetes.io/managed-by: gitops
