resources:
  - ../../base

namespace: ljwx-health

images:
  - name: harbor.eu.lingjingwanxiang.cn/ljwx-health/ljwx-boot
    newName: harbor.eu.lingjingwanxiang.cn/ljwx-health/ljwx-boot
    newTag: "dev-latest"
  - name: harbor.eu.lingjingwanxiang.cn/ljwx-health/ljwx-admin
    newName: harbor.eu.lingjingwanxiang.cn/ljwx-health/ljwx-admin
    newTag: "dev-latest"
  - name: harbor.eu.lingjingwanxiang.cn/ljwx-health/ljwx-bigscreen
    newName: harbor.eu.lingjingwanxiang.cn/ljwx-health/ljwx-bigscreen
    newTag: "dev-latest"
