apiVersion: v1
kind: Secret
metadata:
  name: promoter-secrets
  namespace: shared-platform
type: Opaque
stringData:
  DEPLOY_REPO_TOKEN: "REPLACE_ME"
  HARBOR_USER: "REPLACE_ME"
  HARBOR_PASS: "REPLACE_ME"
