---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ljwx-health

resources:
  - ../../base

images:
  - name: harbor.omniverseai.net/ljwx-health/ljwx-bigscreen
    newTag: "main-1f8b811"
