resources:
  - ../../base
  - db-migration-job.yaml
  - db-migrations-configmap.yaml

namespace: dev

images:
  - name: ghcr.io/brunogaosz/youngth-guard-backend
    newName: ghcr.io/brunogaosz/youngth-guard-backend
    newTag: "dev-b90d0d9"
