apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ljwx-website-dev
resources:
  - ../../base
images:
  - name: harbor.omniverseai.net/ljwx/ljwx-website
    newTag: "main-abde1fb"
replicas:
  - name: ljwx-website
    count: 1
