apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ljwx-bookstore

resources:
  - ../../base

images:
  - name: harbor.omniverseai.net/ljwx/ljwx-bookstore
    newTag: "main-ac40aa9"

replicas:
  - name: ljwx-bookstore
    count: 1
